# Generated by Django 5.2.1 on 2025-07-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_project_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, help_text='A brief description of the project (max 255 characters).', max_length=255, null=True),
        ),
    ]
