# Generated by Django 5.2.1 on 2025-07-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='learned',
            field=models.TextField(blank=True, help_text='what learned', null=True),
        ),
    ]
